import { useEffect, useState } from 'react';
import api from '../lib/api';

const blank = { title: '', description: '', trainerId: '', startTime: '', endTime: '', capacity: '20', location: '', status: 'scheduled' };
const localTime = (value) => value ? new Date(value).toISOString().slice(0, 16) : '';

export default function ClassManagement({ role }) {
  const [classes, setClasses] = useState([]); const [trainers, setTrainers] = useState([]); const [form, setForm] = useState(blank); const [editingId, setEditingId] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const isAdmin = role === 'admin';
  const load = async () => { setLoading(true); try { const calls = [api.get('/classes')]; if (isAdmin) calls.push(api.get('/trainers')); const [classResult, trainerResult] = await Promise.all(calls); setClasses(classResult.data.data || []); if (trainerResult) setTrainers(trainerResult.data.data || []); } catch (err) { setError(err.response?.data?.error || 'Could not load class data.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [isAdmin]);
  const change = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event) { event.preventDefault(); setBusy(true); setError(''); setNotice(''); try { const payload = { ...form, capacity: Number(form.capacity), startTime: new Date(form.startTime).toISOString(), endTime: new Date(form.endTime).toISOString() }; if (!isAdmin) delete payload.trainerId; if (editingId) await api.put(`/classes/${editingId}`, payload); else await api.post('/classes', payload); setNotice(editingId ? 'Class updated.' : 'Class created.'); setEditingId(null); setForm(blank); load(); } catch (err) { setError(err.response?.data?.error || 'Could not save the class.'); } finally { setBusy(false); } }
  function edit(cls) { setEditingId(cls.id); setForm({ title: cls.title, description: cls.description || '', trainerId: String(cls.trainer_id || ''), startTime: localTime(cls.start_time), endTime: localTime(cls.end_time), capacity: String(cls.capacity), location: cls.location || '', status: cls.status || 'scheduled' }); setError(''); setNotice(''); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async function cancel(cls) { setBusy(true); setError(''); setNotice(''); try { await api.put(`/classes/${cls.id}`, { status: 'cancelled' }); setNotice('Class cancelled.'); load(); } catch (err) { setError(err.response?.data?.error || 'Could not cancel the class.'); } finally { setBusy(false); } }
  return <div className="space-y-6">
    {error && <p className="rounded-3xl border border-red-700 bg-red-950/80 px-4 py-3 text-sm text-red-200">{error}</p>}{notice && <p className="rounded-3xl border border-emerald-700 bg-emerald-950/80 px-4 py-3 text-sm text-emerald-200">{notice}</p>}
    <section className="rounded-[2rem] border border-slate-800 bg-slate-900/95 p-6"><h2 className="text-xl font-semibold text-white">{editingId ? 'Edit class' : 'Create class'}</h2><form onSubmit={submit} className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Class name"><input required value={form.title} onChange={(e) => change('title', e.target.value)} className="input" /></Field>{isAdmin && <Field label="Assigned trainer"><select required value={form.trainerId} onChange={(e) => change('trainerId', e.target.value)} className="input"><option value="">Select an active trainer</option>{trainers.map((trainer) => <option key={trainer.id} value={trainer.id}>{trainer.full_name}</option>)}</select></Field>}<Field label="Start"><input required type="datetime-local" value={form.startTime} onChange={(e) => change('startTime', e.target.value)} className="input" /></Field><Field label="End"><input required type="datetime-local" value={form.endTime} onChange={(e) => change('endTime', e.target.value)} className="input" /></Field><Field label="Capacity"><input required type="number" min="1" value={form.capacity} onChange={(e) => change('capacity', e.target.value)} className="input" /></Field><Field label="Location"><input value={form.location} onChange={(e) => change('location', e.target.value)} className="input" placeholder="Studio A" /></Field><Field label="Status"><select value={form.status} onChange={(e) => change('status', e.target.value)} className="input"><option value="scheduled">Scheduled</option><option value="cancelled">Cancelled</option><option value="completed">Completed</option></select></Field><Field label="Description"><textarea value={form.description} onChange={(e) => change('description', e.target.value)} className="input min-h-24" /></Field><div className="flex flex-wrap gap-3 md:col-span-2"><button disabled={busy} className="rounded-3xl bg-emerald-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{busy ? 'Saving…' : editingId ? 'Save changes' : 'Create class'}</button>{editingId && <button type="button" onClick={() => { setEditingId(null); setForm(blank); }} className="rounded-3xl border border-slate-700 px-5 py-3 text-sm text-slate-200">Cancel edit</button>}</div></form></section>
    <section className="rounded-[2rem] border border-slate-800 bg-slate-900/95 p-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold text-white">{isAdmin ? 'All classes' : 'My classes'}</h2><p className="mt-1 text-sm text-slate-400">{isAdmin ? 'Manage schedules across the gym.' : 'You can only manage sessions assigned to you.'}</p></div><span className="text-sm text-slate-400">{loading ? 'Loading…' : `${classes.length} classes`}</span></div>{loading ? <p className="mt-6 text-slate-400">Loading classes…</p> : classes.length === 0 ? <p className="mt-6 rounded-3xl bg-slate-950/70 p-6 text-sm text-slate-400">No classes yet. Create the first session above.</p> : <div className="mt-5 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-slate-500"><tr><th className="p-3">Class</th>{isAdmin && <th className="p-3">Trainer</th>}<th className="p-3">Start</th><th className="p-3">Booked</th><th className="p-3">Status</th><th className="p-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-800">{classes.map((cls) => <tr key={cls.id}><td className="p-3 text-white"><p>{cls.title}</p><p className="text-xs text-slate-500">{cls.location || 'No location'}</p></td>{isAdmin && <td className="p-3 text-slate-400">{cls.trainer_name}</td>}<td className="p-3 text-slate-400">{new Date(cls.start_time).toLocaleString()}</td><td className="p-3 text-slate-400">{cls.booked_count}/{cls.capacity}</td><td className="p-3"><Status value={cls.status} /></td><td className="p-3"><div className="flex gap-2"><button onClick={() => edit(cls)} className="rounded-xl border border-slate-700 px-3 py-2 text-xs text-slate-200">Edit</button>{cls.status === 'scheduled' && <button disabled={busy} onClick={() => cancel(cls)} className="rounded-xl bg-rose-600 px-3 py-2 text-xs text-white disabled:opacity-60">Cancel</button>}</div></td></tr>)}</tbody></table></div>}</section>
  </div>;
}
function Field({ label, children }) { return <label className="text-sm text-slate-300">{label}{children}</label>; }
function Status({ value }) { return <span className={`rounded-full px-2.5 py-1 text-xs capitalize ${value === 'scheduled' ? 'bg-emerald-500/15 text-emerald-300' : value === 'cancelled' ? 'bg-rose-500/15 text-rose-300' : 'bg-slate-800 text-slate-300'}`}>{value}</span>; }
