import { useEffect, useState } from 'react';
import DashboardShell from '../../components/DashboardShell';
import ProtectedRoute from '../../components/ProtectedRoute';
import api from '../../lib/api';

function Features({ value }) { const features = Array.isArray(value) ? value : typeof value === 'string' ? (() => { try { return JSON.parse(value); } catch { return []; } })() : []; return features.length ? <ul className="mt-4 space-y-2 text-sm text-slate-300">{features.map((feature) => <li key={feature}>✓ {feature}</li>)}</ul> : null; }
function Memberships() {
  const [plans, setPlans] = useState([]); const [history, setHistory] = useState([]); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = () => Promise.all([api.get('/memberships/plans'), api.get('/memberships')]).then(([p, h]) => { setPlans(p.data.data || []); setHistory(h.data.data || []); }).catch(() => setError('Unable to load membership details.'));
  useEffect(() => { load(); }, []);
  async function subscribe(id) { setError(''); try { await api.post('/memberships/subscribe', { membershipPlanId: id }); setMessage('Subscription request submitted. It will remain pending until the gym confirms payment.'); load(); } catch (err) { setError(err.response?.data?.error || 'Unable to submit subscription request.'); } }
  return <DashboardShell title="My membership" subtitle="Compare available plans and request a subscription."><div className="space-y-6">{message && <p className="rounded-3xl border border-emerald-700 bg-emerald-950/80 px-4 py-3 text-sm text-emerald-200">{message}</p>}{error && <p className="rounded-3xl border border-red-700 bg-red-950/80 px-4 py-3 text-sm text-red-200">{error}</p>}<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{plans.map((plan) => <article key={plan.id} className="rounded-[2rem] border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold text-white">{plan.name}</h2><p className="mt-3 text-3xl font-semibold text-emerald-300">Rs. {Number(plan.price).toLocaleString()}</p><p className="mt-1 text-sm text-slate-400">{plan.duration_days} days</p><p className="mt-4 text-sm text-slate-400">{plan.description}</p><Features value={plan.features} /><button onClick={() => subscribe(plan.id)} className="mt-6 w-full rounded-2xl bg-emerald-600 px-4 py-3 text-sm font-semibold text-white">Request subscription</button></article>)}</div><section className="rounded-[2rem] border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold text-white">Membership history</h2>{history.length ? <ul className="mt-4 divide-y divide-slate-800">{history.map((item) => <li className="flex justify-between py-3 text-sm" key={item.id}><span className="text-slate-200">{item.plan_name}</span><span className="capitalize text-slate-400">{item.status} · ends {new Date(item.end_date).toLocaleDateString()}</span></li>)}</ul> : <p className="mt-4 text-slate-400">No membership history yet.</p>}</section></div></DashboardShell>;
}
export default function MemberMemberships() { return <ProtectedRoute allowedRoles={['member']}><Memberships /></ProtectedRoute>; }
