import { useEffect, useState } from 'react';
import DashboardShell from '../../components/DashboardShell';
import ProtectedRoute from '../../components/ProtectedRoute';
import api from '../../lib/api';

function AdminMemberships() {
  const [plans, setPlans] = useState([]); const [form, setForm] = useState({ name: '', description: '', price: '', durationDays: '', features: '' }); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = () => api.get('/memberships/plans').then(({ data }) => setPlans(data.data || [])).catch(() => setError('Unable to load plans.'));
  useEffect(() => { load(); }, []);
  const change = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  async function create(event) { event.preventDefault(); setError(''); try { await api.post('/memberships/plans', { name: form.name, description: form.description || null, price: Number(form.price), durationDays: Number(form.durationDays), features: form.features.split('\n').map((value) => value.trim()).filter(Boolean) }); setForm({ name: '', description: '', price: '', durationDays: '', features: '' }); setNotice('Membership plan created.'); load(); } catch (err) { setError(err.response?.data?.error || 'Unable to create membership plan.'); } }
  async function toggle(plan) { try { await api.put(`/memberships/plans/${plan.id}`, { status: plan.status === 'active' ? 'inactive' : 'active' }); load(); } catch (err) { setError(err.response?.data?.error || 'Unable to update plan.'); } }
  return <DashboardShell title="Membership management" subtitle="Configure the plans members can request."><div className="space-y-6">{error && <p className="rounded-3xl border border-red-700 bg-red-950/80 px-4 py-3 text-sm text-red-200">{error}</p>}{notice && <p className="rounded-3xl border border-emerald-700 bg-emerald-950/80 px-4 py-3 text-sm text-emerald-200">{notice}</p>}<section className="rounded-[2rem] border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold text-white">Create plan</h2><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={create}><input required placeholder="Plan name" value={form.name} onChange={(e) => change('name', e.target.value)} className="rounded-2xl border border-slate-800 bg-slate-950 px-4 py-3 text-white"/><input required type="number" min="0" step="0.01" placeholder="Price" value={form.price} onChange={(e) => change('price', e.target.value)} className="rounded-2xl border border-slate-800 bg-slate-950 px-4 py-3 text-white"/><input required type="number" min="1" placeholder="Duration (days)" value={form.durationDays} onChange={(e) => change('durationDays', e.target.value)} className="rounded-2xl border border-slate-800 bg-slate-950 px-4 py-3 text-white"/><textarea placeholder="Description" value={form.description} onChange={(e) => change('description', e.target.value)} className="rounded-2xl border border-slate-800 bg-slate-950 px-4 py-3 text-white"/><textarea placeholder="Features — one per line" value={form.features} onChange={(e) => change('features', e.target.value)} className="min-h-24 rounded-2xl border border-slate-800 bg-slate-950 px-4 py-3 text-white md:col-span-2"/><button className="rounded-2xl bg-emerald-600 px-5 py-3 text-sm font-semibold text-white md:col-span-2">Create membership plan</button></form></section><section className="rounded-[2rem] border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold text-white">Plans</h2><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-slate-500"><tr><th className="p-3">Name</th><th className="p-3">Price</th><th className="p-3">Duration</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody className="divide-y divide-slate-800">{plans.map((plan) => <tr key={plan.id}><td className="p-3 text-white">{plan.name}</td><td className="p-3 text-slate-400">Rs. {Number(plan.price).toLocaleString()}</td><td className="p-3 text-slate-400">{plan.duration_days} days</td><td className="p-3 capitalize text-slate-400">{plan.status}</td><td className="p-3"><button onClick={() => toggle(plan)} className="rounded-xl border border-slate-700 px-3 py-2 text-xs text-white">{plan.status === 'active' ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table></div></section></div></DashboardShell>;
}
export default function AdminMembershipPlans() { return <ProtectedRoute allowedRoles={['admin']}><AdminMemberships /></ProtectedRoute>; }
