import { useEffect, useState } from 'react';
import DashboardShell from '../../components/DashboardShell';
import ProtectedRoute from '../../components/ProtectedRoute';
import api from '../../lib/api';

function MembersPage() {
  const [members, setMembers] = useState([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async (search = '') => { setLoading(true); try { const { data } = await api.get('/users', { params: { role: 'member', search, limit: 50 } }); setMembers(data.data || []); } catch { setError('Unable to load members.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  async function toggle(member) { try { await api.put(`/users/${member.id}`, { isActive: !member.is_active }); setMembers((all) => all.map((item) => item.id === member.id ? { ...item, is_active: !item.is_active } : item)); } catch (err) { setError(err.response?.data?.error || 'Unable to update member.'); } }
  return <DashboardShell title="Member management" subtitle="Search members and control account access."><div className="space-y-6">{error && <p className="rounded-3xl border border-red-700 bg-red-950/80 px-4 py-3 text-sm text-red-200">{error}</p>}<form className="flex gap-3" onSubmit={(e) => { e.preventDefault(); load(query); }}><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search name or email" className="w-full rounded-2xl border border-slate-800 bg-slate-900 px-4 py-3 text-white"/><button className="rounded-2xl bg-emerald-600 px-5 py-3 text-sm font-semibold text-white">Search</button></form><section className="rounded-[2rem] border border-slate-800 bg-slate-900/95 p-6">{loading ? <p className="text-slate-400">Loading members…</p> : members.length === 0 ? <p className="text-slate-400">No members found.</p> : <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-800 text-slate-500"><tr><th className="p-3">Member</th><th className="p-3">Contact</th><th className="p-3">Joined</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody className="divide-y divide-slate-800">{members.map((member) => <tr key={member.id}><td className="p-3 font-medium text-white">{member.full_name}</td><td className="p-3 text-slate-400">{member.email}<br />{member.phone || '—'}</td><td className="p-3 text-slate-400">{new Date(member.created_at).toLocaleDateString()}</td><td className="p-3"><span className={member.is_active ? 'text-emerald-300' : 'text-rose-300'}>{member.is_active ? 'Active' : 'Inactive'}</span></td><td className="p-3"><button onClick={() => toggle(member)} className="rounded-xl border border-slate-700 px-3 py-2 text-xs text-slate-200">{member.is_active ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table></div>}</section></div></DashboardShell>;
}
export default function AdminMembers() { return <ProtectedRoute allowedRoles={['admin']}><MembersPage /></ProtectedRoute>; }
