import { useEffect, useState } from 'react';
import DashboardShell from '../../components/DashboardShell';
import ProtectedRoute from '../../components/ProtectedRoute';
import api from '../../lib/api';

const blank = { fullName: '', email: '', password: '', phone: '', specialization: '', experienceYears: '', maxMembers: '20', availabilityNote: '', personalTrainingCost: '' };

function TrainersAdminPage() {
  const [trainers, setTrainers] = useState([]); const [requests, setRequests] = useState([]); const [form, setForm] = useState(blank); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => Promise.all([api.get('/trainers'), api.get('/trainer-requests')]).then(([t, r]) => { setTrainers(t.data.data || []); setRequests(r.data.data || []); }).catch(() => setError('Unable to load trainer management data.')).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);
  const update = (key, value) => setForm((prev) => ({ ...prev, [key]: value }));
  async function createTrainer(event) { event.preventDefault(); setError(''); setNotice(''); try { const { data } = await api.post('/users', { fullName: form.fullName, email: form.email, password: form.password, phone: form.phone || null, role: 'trainer' }); await api.put(`/trainers/${data.id}/profile`, { specialization: form.specialization || null, experienceYears: form.experienceYears ? Number(form.experienceYears) : null, maxMembers: Number(form.maxMembers), availabilityNote: form.availabilityNote || null, personalTrainingCost: form.personalTrainingCost ? Number(form.personalTrainingCost) : null }); setForm(blank); setNotice('Trainer created and ready to receive requests.'); load(); } catch (err) { setError(err.response?.data?.error || 'Unable to create trainer.'); } }
  async function approve(id) { setError(''); try { await api.patch(`/trainer-requests/${id}/approve`); setNotice('Trainer request approved and assignment created.'); load(); } catch (err) { setError(err.response?.data?.error || 'Unable to approve request.'); } }
  return <DashboardShell title="Trainer management" subtitle="Create trainers, review capacity, and approve member requests."><div className="space-y-6">
    {error && <p className="rounded-3xl border border-red-700 bg-red-950/80 px-4 py-3 text-sm text-red-200">{error}</p>}{notice && <p className="rounded-3xl border border-emerald-700 bg-emerald-950/80 px-4 py-3 text-sm text-emerald-200">{notice}</p>}
    <section className="rounded-[2rem] border border-slate-800 bg-slate-900/95 p-6"><h2 className="text-xl font-semibold text-white">Create trainer</h2><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={createTrainer}>{[['fullName','Name'],['email','Email'],['phone','Phone'],['specialization','Specialization'],['experienceYears','Experience (years)'],['maxMembers','Member capacity'],['availabilityNote','Availability'],['personalTrainingCost','Personal-training cost']].map(([key,label]) => <label key={key} className="text-sm text-slate-300">{label}<input required={['fullName','email','experienceYears','maxMembers'].includes(key)} type={key === 'email' ? 'email' : ['experienceYears','maxMembers','personalTrainingCost'].includes(key) ? 'number' : 'text'} min={['experienceYears','maxMembers','personalTrainingCost'].includes(key) ? 0 : undefined} value={form[key]} onChange={(e) => update(key, e.target.value)} className="mt-2 w-full rounded-2xl border border-slate-800 bg-slate-950 px-3 py-2 text-white" /></label>)}<label className="text-sm text-slate-300">Temporary password<input required type="password" minLength="8" value={form.password} onChange={(e) => update('password', e.target.value)} className="mt-2 w-full rounded-2xl border border-slate-800 bg-slate-950 px-3 py-2 text-white" /></label><div className="flex items-end"><button className="w-full rounded-2xl bg-emerald-600 px-4 py-3 text-sm font-semibold text-white hover:bg-emerald-500">Create trainer</button></div></form></section>
    <section className="rounded-[2rem] border border-slate-800 bg-slate-900/95 p-6"><h2 className="text-xl font-semibold text-white">Pending requests</h2>{loading ? <p className="mt-4 text-slate-400">Loading…</p> : requests.filter((r) => r.status === 'pending').length === 0 ? <p className="mt-4 text-sm text-slate-400">No pending trainer requests.</p> : <div className="mt-4 space-y-3">{requests.filter((r) => r.status === 'pending').map((r) => <div key={r.id} className="flex flex-col gap-3 rounded-2xl bg-slate-950 p-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-slate-200"><span className="font-semibold">{r.member_name}</span> requested <span className="font-semibold">{r.trainer_name}</span></p><button onClick={() => approve(r.id)} className="rounded-2xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Approve</button></div>)}</div>}</section>
    <section className="rounded-[2rem] border border-slate-800 bg-slate-900/95 p-6"><h2 className="text-xl font-semibold text-white">Trainer workload</h2><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-slate-500"><tr><th className="p-3">Trainer</th><th className="p-3">Specialization</th><th className="p-3">Availability</th><th className="p-3">Members</th></tr></thead><tbody className="divide-y divide-slate-800">{trainers.map((t) => <tr key={t.id}><td className="p-3 text-white">{t.full_name}</td><td className="p-3 text-slate-400">{t.specialization || 'General fitness'}</td><td className="p-3 text-slate-400">{t.is_available ? 'Available' : 'Unavailable'}</td><td className="p-3 text-slate-400">{t.assigned_members}/{t.max_members || 20}</td></tr>)}</tbody></table></div></section>
  </div></DashboardShell>;
}
export default function AdminTrainers() { return <ProtectedRoute allowedRoles={['admin']}><TrainersAdminPage /></ProtectedRoute>; }
